# Load libraries
####################################################
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

library("ComplexHeatmap")
library("DESeq2")
library("GSVA")
library("GSVAdata")
library("GenomicFeatures")
library("NMF")
library("RColorBrewer")
library("biomaRt")
library("devtools")
library("ggplot2")
library("goseq")
library("gplots")
library("gtools")
library("hexbin")
library("limma")
library("pheatmap")
library("readr")
library("rjson")
library("tximport")
library("vsn")
library("nclust")
library("circlize")
library("sva")
library("DOSE")
library("pathview")
library("clusterProfiler")
library("ggrepel")
library("ggpubr")
library("viridis")
library("grid")
library("lattice")
library("gridExtra")
library("ArrayTools")
library("openxlsx")
library("fastICA")

# install.packages("devtools")
#devtools::install_github("zhangyuqing/sva-devel")

#if (!requireNamespace("BiocManager", quietly = TRUE))
#  install.packages("BiocManager")
#
#BiocManager::install("DESeq2")
